import {
  ArrowDown,
  ArrowUp,
  BarChart,
  Bell,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronsLeft,
  ChevronsRight,
  ChevronsUpDown,
  CircleDollarSign,
  CircleUser,
  Columns,
  EyeOff,
  Facebook,
  Home,
  Image,
  Instagram,
  Linkedin,
  List,
  LoaderIcon,
  LogOut,
  Menu,
  Moon,
  Pencil,
  Plus,
  PlusCircle,
  Repeat,
  Settings,
  SlidersHorizontal,
  Sun,
  Trash,
  Twitter,
  UserCheck,
  Users,
  UserX,
  View,
  WalletCards,
  X,
} from 'lucide-react'

export const Icons = {
  addCircle: PlusCircle,
  arrowDown: ArrowDown,
  arrowUp: ArrowUp,
  barChart: BarChart,
  check: Check,
  columns: Columns,
  costumers: Users,
  chevronDown: ChevronDown,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  chevronsLeft: ChevronsLeft,
  chevronsRight: ChevronsRight,
  edit: Pencil,
  facebook: Facebook,
  hide: EyeOff,
  home: Home,
  instagram: Instagram,
  installments: WalletCards,
  linkedin: Linkedin,
  list: List,
  logout: LogOut,
  menu: Menu,
  money: CircleDollarSign,
  moon: Moon,
  new: Plus,
  notifications: Bell,
  placeholder: Image,
  repeat: Repeat,
  settings: Settings,
  settingsHorizontal: SlidersHorizontal,
  spinner: LoaderIcon,
  sun: Sun,
  trash: Trash,
  twitter: Twitter,
  updown: ChevronsUpDown,
  user: CircleUser,
  user_active: UserCheck,
  user_inactive: UserX,
  view: View,
  x: X,
}
